const productos = [
  {
    Artículo: "Adaptador de compresor",
    Precio: "$10,00",
    link: "./images/rory.jpg",
  },
  {
    Artículo: "Ángulo galvanizado 45mm",
    Precio: "$1,00",
    link: "./images/rory.jpg",
  },
  {
    Artículo: "Ángulo prepintado (10 pies)",
    Precio: "$1,50",
    link: "./images/rory.jpg",
  },
  { Artículo: "Baquetón", Precio: "$7,00", link: "./images/rory.jpg" },
  { Artículo: "Batidora", Precio: "$10,00", link: "./images/rory.jpg" },
  { Artículo: "Bolsa de cemento", Precio: "$7,50", link: "./images/rory.jpg" },
  { Artículo: "Broca 1/2", Precio: "$2,50", link: "./images/rory.jpg" },
  { Artículo: "Broca 1/4", Precio: "$1,50", link: "./images/rory.jpg" },
  { Artículo: "Broca 3/16", Precio: "$1,50", link: "./images/rory.jpg" },
  { Artículo: "Broca 3/8", Precio: "$2,00", link: "./images/rory.jpg" },
  { Artículo: "Broca 5/16", Precio: "$1,75", link: "./images/rory.jpg" },
  { Artículo: "Broca 5/32", Precio: "$1,50", link: "./images/rory.jpg" },
  { Artículo: "Broca 7/32", Precio: "$1,50", link: "./images/rory.jpg" },
  {
    Artículo: "Cable #10 (por metro)",
    Precio: "$1,20",
    link: "./images/rory.jpg",
  },
  {
    Artículo: "Cable #12 (por metro)",
    Precio: "$0,90",
    link: "./images/rory.jpg",
  },
  {
    Artículo: "Cable #14 (por metro)",
    Precio: "$0,70",
    link: "./images/rory.jpg",
  },
  { Artículo: "Caja 4x4", Precio: "$0,80", link: "./images/rory.jpg" },
  { Artículo: "Caja rectangular", Precio: "$0,60", link: "./images/rory.jpg" },
  { Artículo: "Candado 40mm", Precio: "$4,50", link: "./images/rory.jpg" },
  { Artículo: "Candado 50mm", Precio: "$5,50", link: "./images/rory.jpg" },
  { Artículo: "Cinta aislante", Precio: "$1,00", link: "./images/rory.jpg" },
  { Artículo: "Cinta de medir 5m", Precio: "$3,50", link: "./images/rory.jpg" },
  { Artículo: "Clavo 2 1/2", Precio: "$1,50", link: "./images/rory.jpg" },
  { Artículo: "Clavo 3", Precio: "$1,50", link: "./images/rory.jpg" },
  { Artículo: "Clavo 4", Precio: "$1,50", link: "./images/rory.jpg" },
  { Artículo: "Conector 1/2", Precio: "$0,30", link: "./images/rory.jpg" },
  { Artículo: "Cople 1/2", Precio: "$0,30", link: "./images/rory.jpg" },
  {
    Artículo: "Disco de corte 4 1/2",
    Precio: "$2,00",
    link: "./images/rory.jpg",
  },
  {
    Artículo: "Disco de desbaste 4 1/2",
    Precio: "$2,00",
    link: "./images/rory.jpg",
  },
  { Artículo: "Duplex", Precio: "$1,00", link: "./images/rory.jpg" },
  { Artículo: "Electrodos 3/32", Precio: "$5,00", link: "./images/rory.jpg" },
  { Artículo: "Electrodos 1/8", Precio: "$5,00", link: "./images/rory.jpg" },
  { Artículo: "Escobillón", Precio: "$3,00", link: "./images/rory.jpg" },
  { Artículo: "Espátula 2", Precio: "$1,50", link: "./images/rory.jpg" },
  { Artículo: "Espátula 3", Precio: "$1,80", link: "./images/rory.jpg" },
  { Artículo: "Espátula 4", Precio: "$2,00", link: "./images/rory.jpg" },
  { Artículo: "Extensión 5m", Precio: "$6,00", link: "./images/rory.jpg" },
  { Artículo: "Foco LED 9W", Precio: "$2,00", link: "./images/rory.jpg" },
  { Artículo: "Foco LED 12W", Precio: "$2,50", link: "./images/rory.jpg" },
  { Artículo: "Grifa", Precio: "$5,00", link: "./images/rory.jpg" },
  {
    Artículo: "Guantes de nitrilo",
    Precio: "$1,00",
    link: "./images/rory.jpg",
  },
  {
    Artículo: "Interruptor sencillo",
    Precio: "$1,20",
    link: "./images/rory.jpg",
  },
  { Artículo: "Lija de agua", Precio: "$0,50", link: "./images/rory.jpg" },
  { Artículo: "Lija para madera", Precio: "$0,50", link: "./images/rory.jpg" },
  { Artículo: "Limatón", Precio: "$2,50", link: "./images/rory.jpg" },
  { Artículo: "Llave de paso 1/2", Precio: "$4,00", link: "./images/rory.jpg" },
  { Artículo: "Llave inglesa", Precio: "$6,00", link: "./images/rory.jpg" },
  {
    Artículo: "Manguera 1/2 (por metro)",
    Precio: "$0,80",
    link: "./images/rory.jpg",
  },
  { Artículo: "Martillo", Precio: "$5,50", link: "./images/rory.jpg" },
  { Artículo: "Masilla plástica", Precio: "$4,00", link: "./images/rory.jpg" },
  { Artículo: "Niple 1/2", Precio: "$0,50", link: "./images/rory.jpg" },
  { Artículo: "Pega instantánea", Precio: "$1,50", link: "./images/rory.jpg" },
  {
    Artículo: "Pegamento de contacto",
    Precio: "$3,00",
    link: "./images/rory.jpg",
  },
  { Artículo: "Pincel 1", Precio: "$0,80", link: "./images/rory.jpg" },
  { Artículo: "Pincel 2", Precio: "$1,00", link: "./images/rory.jpg" },
  { Artículo: "Pincel 3", Precio: "$1,20", link: "./images/rory.jpg" },
  { Artículo: "Rodillo", Precio: "$2,50", link: "./images/rory.jpg" },
  { Artículo: "Segueta", Precio: "$1,00", link: "./images/rory.jpg" },
  { Artículo: "Silicona", Precio: "$2,00", link: "./images/rory.jpg" },
  { Artículo: "Taladro", Precio: "$45,00", link: "./images/rory.jpg" },
  { Artículo: "Teflón", Precio: "$0,50", link: "./images/rory.jpg" },
  {
    Artículo: "Tijera de hojalatero",
    Precio: "$5,00",
    link: "./images/rory.jpg",
  },
  {
    Artículo: "Tornillo autorroscante",
    Precio: "$0,10",
    link: "./images/rory.jpg",
  },
  { Artículo: "Tubo PVC 1/2", Precio: "$2,00", link: "./images/rory.jpg" },
  { Artículo: "Tubo PVC 3/4", Precio: "$2,50", link: "./images/rory.jpg" },
];
