const productos = [
  {
    producto: "Adaptador de compresor",
    precio: "$10,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Ángulo galvanizado 45mm",
    precio: "$1,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Ángulo prepintado (10 pies)",
    precio: "$1,50",
    link: "./images/rory.jpg",
  },
  { producto: "Baquetón", precio: "$7,00", link: "./images/rory.jpg" },
  { producto: "Batidora", precio: "$10,00", link: "./images/rory.jpg" },
  {
    producto: "Bolsa de 100 tornillo para taco",
    precio: "$2,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Bolsa de 100 tornillos punta de broca  y aleta",
    precio: "$3,00",
    link: "./images/rory.jpg",
  },
  { producto: "Bolsa de Romeral", precio: "$20,00", link: "./images/rory.jpg" },
  {
    producto: "Bolsita de 100 clavo de acero negro",
    precio: "$1,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Bolsita de 100 tacos filler F5",
    precio: "$2,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Bolsita de 100 tacos filler F6",
    precio: "$2,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Bolsita de 100 tornillos punta de broca con cabeza bellanada",
    precio: "$7,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Bolsita de 100 tornillos para plancha",
    precio: "$1,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Bolsita de 100 tornillos punta de broca  ",
    precio: "$2,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Bolsita de 100 tornillos punta fina",
    precio: "$1,00",
    link: "./images/rory.jpg",
  },
  { producto: "Broca 5mm", precio: "$5,00", link: "./images/rory.jpg" },
  {
    producto: "Caja de 100 clavo de acero blanco",
    precio: "$3,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Caja de 2000 clavos de acero negro",
    precio: "$20,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Caja de clavos de acero negro ",
    precio: "$18,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Caja de fulminantes  con caja clavo de impacto",
    precio: "$16,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Caja de tornillos para plancha ",
    precio: "$8,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Caja fulminante y clavo de impacto de correa",
    precio: "$18,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Caneca de Pintura",
    precio: "$45,00",
    link: "./images/rory.jpg",
  },
  { producto: "Cenefa", precio: "$9,00", link: "./images/rory.jpg" },
  { producto: "Chaveta de fierro", precio: "$5,00", link: "./images/rory.jpg" },
  { producto: "Clavo líquido", precio: "$5,00", link: "./images/rory.jpg" },
  {
    producto: "Clavos de impacto para pistola",
    precio: "$9,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Espaldón o primario",
    precio: "$2,80",
    link: "./images/rory.jpg",
  },
  {
    producto: "Chaveta de plastico",
    precio: "$3,00",
    link: "./images/rory.jpg",
  },
  { producto: "Estud 2 1/2", precio: "$2,70", link: "./images/rory.jpg" },
  { producto: "Estud de 1 5/8", precio: "$2,50", link: "./images/rory.jpg" },
  { producto: "Estud de 2 1/2", precio: "$2,50", link: "./images/rory.jpg" },
  { producto: "Estud de 3 5/8 ", precio: "$3,00", link: "./images/rory.jpg" },
  {
    producto: "Foco bombilla led",
    precio: "$10,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Foco cuadrado (grande)",
    precio: "$8,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Foco redondo (pequeño)",
    precio: "$5,00",
    link: "./images/rory.jpg",
  },
  { producto: "Foco sensor", precio: "$5,00", link: "./images/rory.jpg" },
  { producto: "Mezcladora", precio: "$120,00", link: "./images/rory.jpg" },
  {
    producto: "Omega o secundario",
    precio: "$3,00",
    link: "./images/rory.jpg",
  },
  { producto: "Omega para PVC", precio: "$2,20", link: "./images/rory.jpg" },
  {
    producto: "Pistola de clavos",
    precio: "$25,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Plancha de fibrocemento 6mm",
    precio: "$17,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Plancha de fibrocemento 8mm",
    precio: "$23,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Plancha de Gypsum KANAUF",
    precio: "$11,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Plancha de Gypsum Panel Rey",
    precio: "$11,75",
    link: "./images/rory.jpg",
  },
  {
    producto: "Plancha de Gypsum verde",
    precio: "$16,00",
    link: "./images/rory.jpg",
  },
  { producto: "Plancha de Luver", precio: "$8,00", link: "./images/rory.jpg" },
  { producto: "Plancha de PVC ", precio: "$3,00", link: "./images/rory.jpg" },
  {
    producto: "Plancha de Gypsum Vinil",
    precio: "$2,80",
    link: "./images/rory.jpg",
  },
  {
    producto: "Rollo cinta de malla",
    precio: "$4,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Rollo cinta de papel",
    precio: "$3,50",
    link: "./images/rory.jpg",
  },
  {
    producto: "Rollo de cinta doble FAX",
    precio: "$3,00",
    link: "./images/rory.jpg",
  },
  { producto: "Silicon blanco", precio: "$3,00", link: "./images/rory.jpg" },
  { producto: "T-2 ", precio: "$0,50", link: "./images/rory.jpg" },
  { producto: "T-4", precio: "$1,00", link: "./images/rory.jpg" },
  { producto: "T-12", precio: "$3,00", link: "./images/rory.jpg" },
  {
    producto: "Taco especial para Gypsum",
    precio: "$0,30",
    link: "./images/rory.jpg",
  },
  { producto: "Taladro 35w", precio: "$80,00", link: "./images/rory.jpg" },
  { producto: "Taladro de 128w", precio: "$128,00", link: "./images/rory.jpg" },
  {
    producto: "Taladro eléctrico",
    precio: "$70,00",
    link: "./images/rory.jpg",
  },
  {
    producto: "Tijeras de acero negro",
    precio: "$10,00",
    link: "./images/rory.jpg",
  },
  { producto: "Trak de 1 5/8", precio: "$2,30", link: "./images/rory.jpg" },
  { producto: "Trak de 2 1/2", precio: "$2,50", link: "./images/rory.jpg" },
  { producto: "Trak de 3 5/8", precio: "$3,00", link: "./images/rory.jpg" },
  { producto: "Traslúcido", precio: "$8,00", link: "./images/rory.jpg" },
];

export { productos };
